# Generated by Django 4.0.5 on 2022-06-12 17:02

import awards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50)),
                ('image_caption', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, null=True, upload_to=awards.models.user_directory_path)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
