# Generated by Django 4.0.5 on 2022-06-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_caption',
            new_name='image_description',
        ),
    ]
